"""updated TicketAssignee model

Revision ID: 24af6f6143d2
Revises: b7ab95fd356c
Create Date: 2024-09-18 09:49:45.849013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24af6f6143d2'
down_revision = 'b7ab95fd356c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_assignees', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_assignees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
